#!/usr/bin/env bash
# install-sai-aliases.sh — derive `sai.<botname>` aliases from .sai/agents.yaml into /root/.bashrc.
# Generated block is marker-delimited; re-running is idempotent; retired bots lose their alias.
set -euo pipefail
HARNESS_DIR="$(cd "$(dirname "$0")/.." && pwd)"   # .sai/
YAML="$HARNESS_DIR/agents.yaml"
BASHRC="${SAI_BASHRC:-/root/.bashrc}"
BEGIN="# BEGIN sai fleet channels (generated by install-sai-aliases.sh — do not hand-edit)"
END="# END sai fleet channels"

ids=$(python3 -c '
import sys, yaml
doc = yaml.safe_load(open(sys.argv[1])) or {}
for a in doc.get("agents", []):
    i = a.get("id")
    if isinstance(i, str) and i.strip():
        print(i.strip())
' "$YAML")

block="$BEGIN"
for id in $ids; do
  block+=$'\n'"alias sai.$id='sai-attach $id'"
done
block+=$'\n'"$END"$'\n'

touch "$BASHRC"
python3 - "$BASHRC" <<PYEOF
import sys, re
path, begin, end = sys.argv[1], """$BEGIN""", """$END"""
src = open(path).read()
pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end) + r"\n?", re.S)
if pattern.search(src):
    src = pattern.sub("", src)          # strip old block; fall through to append fresh
open(path, "w").write(src.rstrip("\n") + "\n")
PYEOF

printf '%s\n' "$block" >> "$BASHRC"
printf '[sai] aliases installed for: %s\n' "$(echo $ids | tr '\n' ' ')"
